---
# yamllint disable rule:line-length
name: ansel-bin copr rebuild
on:
  push:
    branches:
      - main
    paths:
      - tools-misc/ansel-bin/ansel-bin.spec
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-slim
    steps:
      - name: Run webhook for copr
        run: |
          curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/${{ secrets.COPR_TOOLS_MISC }}/ansel-bin
