---
# yamllint disable rule:line-length
name: bun-bin copr rebuild
on:
  push:
    branches:
      - main
    paths:
      - tools-misc/bun-bin/bun-bin.spec
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-slim
    steps:
      - name: Run webhook for copr
        run: |
          curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/${{ secrets.COPR_TOOLS_MISC }}/bun-bin
