---
# yamllint disable rule:line-length
name: dfu-programmer copr rebuild
on:
  push:
    branches:
      - main
    paths:
      - tools-misc/dfu-programmer/dfu-programmer.spec
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-slim
    steps:
      - name: Run webhook for copr
        run: |
          curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/${{ secrets.COPR_TOOLS_MISC }}/dfu-programmer
