---
name: renovate runner
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 7" # Sunday 8 UTC
jobs:
  renovate:
    name: Run renovate in repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
